#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using oDataModel;

namespace oDataModel	
{
	public partial class Appearance
	{
		private short _yearID;
		public virtual short yearID
		{
			get
			{
				return this._yearID;
			}
			set
			{
				this._yearID = value;
			}
		}
		
		private string _teamID;
		public virtual string teamID
		{
			get
			{
				return this._teamID;
			}
			set
			{
				this._teamID = value;
			}
		}
		
		private string _lgID;
		public virtual string lgID
		{
			get
			{
				return this._lgID;
			}
			set
			{
				this._lgID = value;
			}
		}
		
		private string _playerID;
		public virtual string playerID
		{
			get
			{
				return this._playerID;
			}
			set
			{
				this._playerID = value;
			}
		}
		
		private short? _G_all;
		public virtual short? G_all
		{
			get
			{
				return this._G_all;
			}
			set
			{
				this._G_all = value;
			}
		}
		
		private short? _GS;
		public virtual short? GS
		{
			get
			{
				return this._GS;
			}
			set
			{
				this._GS = value;
			}
		}
		
		private short? _G_batting;
		public virtual short? G_batting
		{
			get
			{
				return this._G_batting;
			}
			set
			{
				this._G_batting = value;
			}
		}
		
		private short? _G_defense;
		public virtual short? G_defense
		{
			get
			{
				return this._G_defense;
			}
			set
			{
				this._G_defense = value;
			}
		}
		
		private short? _G_p;
		public virtual short? G_p
		{
			get
			{
				return this._G_p;
			}
			set
			{
				this._G_p = value;
			}
		}
		
		private short? _G_c;
		public virtual short? G_c
		{
			get
			{
				return this._G_c;
			}
			set
			{
				this._G_c = value;
			}
		}
		
		private short? _G_1b;
		public virtual short? G_1b
		{
			get
			{
				return this._G_1b;
			}
			set
			{
				this._G_1b = value;
			}
		}
		
		private short? _G_2b;
		public virtual short? G_2b
		{
			get
			{
				return this._G_2b;
			}
			set
			{
				this._G_2b = value;
			}
		}
		
		private short? _G_3b;
		public virtual short? G_3b
		{
			get
			{
				return this._G_3b;
			}
			set
			{
				this._G_3b = value;
			}
		}
		
		private short? _G_ss;
		public virtual short? G_ss
		{
			get
			{
				return this._G_ss;
			}
			set
			{
				this._G_ss = value;
			}
		}
		
		private short? _G_lf;
		public virtual short? G_lf
		{
			get
			{
				return this._G_lf;
			}
			set
			{
				this._G_lf = value;
			}
		}
		
		private short? _G_cf;
		public virtual short? G_cf
		{
			get
			{
				return this._G_cf;
			}
			set
			{
				this._G_cf = value;
			}
		}
		
		private short? _G_rf;
		public virtual short? G_rf
		{
			get
			{
				return this._G_rf;
			}
			set
			{
				this._G_rf = value;
			}
		}
		
		private short? _G_of;
		public virtual short? G_of
		{
			get
			{
				return this._G_of;
			}
			set
			{
				this._G_of = value;
			}
		}
		
		private short? _G_dh;
		public virtual short? G_dh
		{
			get
			{
				return this._G_dh;
			}
			set
			{
				this._G_dh = value;
			}
		}
		
		private short? _G_ph;
		public virtual short? G_ph
		{
			get
			{
				return this._G_ph;
			}
			set
			{
				this._G_ph = value;
			}
		}
		
		private short? _G_pr;
		public virtual short? G_pr
		{
			get
			{
				return this._G_pr;
			}
			set
			{
				this._G_pr = value;
			}
		}
		
		private string _teamIDyearID;
		public virtual string teamIDyearID
		{
			get
			{
				return this._teamIDyearID;
			}
			set
			{
				this._teamIDyearID = value;
			}
		}
		
		private Master _Master;
		public virtual Master Master
		{
			get
			{
				return this._Master;
			}
			set
			{
				this._Master = value;
			}
		}
		
		private Team _Team;
		public virtual Team Team
		{
			get
			{
				return this._Team;
			}
			set
			{
				this._Team = value;
			}
		}
		
	}
}
#pragma warning restore 1591
