#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using oDataModel;

namespace oDataModel	
{
	public partial class Master
	{
		private string _playerID;
		public virtual string playerID
		{
			get
			{
				return this._playerID;
			}
			set
			{
				this._playerID = value;
			}
		}
		
		private short? _birthYear;
		public virtual short? birthYear
		{
			get
			{
				return this._birthYear;
			}
			set
			{
				this._birthYear = value;
			}
		}
		
		private short? _birthMonth;
		public virtual short? birthMonth
		{
			get
			{
				return this._birthMonth;
			}
			set
			{
				this._birthMonth = value;
			}
		}
		
		private short? _birthDay;
		public virtual short? birthDay
		{
			get
			{
				return this._birthDay;
			}
			set
			{
				this._birthDay = value;
			}
		}
		
		private string _birthCountry;
		public virtual string birthCountry
		{
			get
			{
				return this._birthCountry;
			}
			set
			{
				this._birthCountry = value;
			}
		}
		
		private string _birthState;
		public virtual string birthState
		{
			get
			{
				return this._birthState;
			}
			set
			{
				this._birthState = value;
			}
		}
		
		private string _birthCity;
		public virtual string birthCity
		{
			get
			{
				return this._birthCity;
			}
			set
			{
				this._birthCity = value;
			}
		}
		
		private short? _deathYear;
		public virtual short? deathYear
		{
			get
			{
				return this._deathYear;
			}
			set
			{
				this._deathYear = value;
			}
		}
		
		private short? _deathMonth;
		public virtual short? deathMonth
		{
			get
			{
				return this._deathMonth;
			}
			set
			{
				this._deathMonth = value;
			}
		}
		
		private short? _deathDay;
		public virtual short? deathDay
		{
			get
			{
				return this._deathDay;
			}
			set
			{
				this._deathDay = value;
			}
		}
		
		private string _deathCountry;
		public virtual string deathCountry
		{
			get
			{
				return this._deathCountry;
			}
			set
			{
				this._deathCountry = value;
			}
		}
		
		private string _deathState;
		public virtual string deathState
		{
			get
			{
				return this._deathState;
			}
			set
			{
				this._deathState = value;
			}
		}
		
		private string _deathCity;
		public virtual string deathCity
		{
			get
			{
				return this._deathCity;
			}
			set
			{
				this._deathCity = value;
			}
		}
		
		private string _nameFirst;
		public virtual string nameFirst
		{
			get
			{
				return this._nameFirst;
			}
			set
			{
				this._nameFirst = value;
			}
		}
		
		private string _nameLast;
		public virtual string nameLast
		{
			get
			{
				return this._nameLast;
			}
			set
			{
				this._nameLast = value;
			}
		}
		
		private string _nameGiven;
		public virtual string nameGiven
		{
			get
			{
				return this._nameGiven;
			}
			set
			{
				this._nameGiven = value;
			}
		}
		
		private short? _weight;
		public virtual short? weight
		{
			get
			{
				return this._weight;
			}
			set
			{
				this._weight = value;
			}
		}
		
		private double? _height;
		public virtual double? height
		{
			get
			{
				return this._height;
			}
			set
			{
				this._height = value;
			}
		}
		
		private string _bats;
		public virtual string bats
		{
			get
			{
				return this._bats;
			}
			set
			{
				this._bats = value;
			}
		}
		
		private string _throws;
		public virtual string throws
		{
			get
			{
				return this._throws;
			}
			set
			{
				this._throws = value;
			}
		}
		
		private DateTime? _debut;
		public virtual DateTime? debut
		{
			get
			{
				return this._debut;
			}
			set
			{
				this._debut = value;
			}
		}
		
		private DateTime? _finalGame;
		public virtual DateTime? finalGame
		{
			get
			{
				return this._finalGame;
			}
			set
			{
				this._finalGame = value;
			}
		}
		
		private string _retroID;
		public virtual string retroID
		{
			get
			{
				return this._retroID;
			}
			set
			{
				this._retroID = value;
			}
		}
		
		private string _bbrefID;
		public virtual string bbrefID
		{
			get
			{
				return this._bbrefID;
			}
			set
			{
				this._bbrefID = value;
			}
		}
		
		private IList<Appearance> _Appearances = new List<Appearance>();
		public virtual IList<Appearance> Appearances
		{
			get
			{
				return this._Appearances;
			}
		}
		
	}
}
#pragma warning restore 1591
