#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ContextGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using oDataModel;

namespace oDataModel	
{
	public partial class EntitiesModel : OpenAccessContext, IEntitiesModelUnitOfWork
	{
		private static string connectionStringName = @"LahmanConnection";
			
		private static BackendConfiguration backend = GetBackendConfiguration();
				
		private static MetadataSource metadataSource = XmlMetadataSource.FromAssemblyResource("oData.rlinq");
		
		public EntitiesModel()
			:base(connectionStringName, backend, metadataSource)
		{ }
		
		public EntitiesModel(string connection)
			:base(connection, backend, metadataSource)
		{ }
		
		public EntitiesModel(BackendConfiguration backendConfiguration)
			:base(connectionStringName, backendConfiguration, metadataSource)
		{ }
			
		public EntitiesModel(string connection, MetadataSource metadataSource)
			:base(connection, backend, metadataSource)
		{ }
		
		public EntitiesModel(string connection, BackendConfiguration backendConfiguration, MetadataSource metadataSource)
			:base(connection, backendConfiguration, metadataSource)
		{ }
			
		public IQueryable<Team> Teams 
		{
			get
			{
				return this.GetAll<Team>();
			}
		}
		
		public IQueryable<Master> Masters 
		{
			get
			{
				return this.GetAll<Master>();
			}
		}
		
		public IQueryable<Appearance> Appearances 
		{
			get
			{
				return this.GetAll<Appearance>();
			}
		}
		
		public IQueryable<vTeam> vTeams 
		{
			get
			{
				return this.GetAll<vTeam>();
			}
		}
		
		public IQueryable<vTeams_by_Year> vTeams_by_Years 
		{
			get
			{
				return this.GetAll<vTeams_by_Year>();
			}
		}
		
		public IQueryable<vSalaries_by_Year> vSalaries_by_Years 
		{
			get
			{
				return this.GetAll<vSalaries_by_Year>();
			}
		}
		
		public static BackendConfiguration GetBackendConfiguration()
		{
			BackendConfiguration backend = new BackendConfiguration();
			backend.Backend = "MsSql";
			backend.ProviderName = "System.Data.SqlClient";
		
			CustomizeBackendConfiguration(ref backend);
		
			return backend;
		}
		
		/// <summary>
		/// Allows you to customize the BackendConfiguration of EntitiesModel.
		/// </summary>
		/// <param name="config">The BackendConfiguration of EntitiesModel.</param>
		static partial void CustomizeBackendConfiguration(ref BackendConfiguration config);
		
	}
	
	public interface IEntitiesModelUnitOfWork : IUnitOfWork
	{
		IQueryable<Team> Teams
		{
			get;
		}
		IQueryable<Master> Masters
		{
			get;
		}
		IQueryable<Appearance> Appearances
		{
			get;
		}
		IQueryable<vTeam> vTeams
		{
			get;
		}
		IQueryable<vTeams_by_Year> vTeams_by_Years
		{
			get;
		}
		IQueryable<vSalaries_by_Year> vSalaries_by_Years
		{
			get;
		}
	}
}
#pragma warning restore 1591
