#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using oDataModel;

namespace oDataModel	
{
	public partial class Team
	{
		private short _yearID;
		public virtual short yearID
		{
			get
			{
				return this._yearID;
			}
			set
			{
				this._yearID = value;
			}
		}
		
		private string _lgID;
		public virtual string lgID
		{
			get
			{
				return this._lgID;
			}
			set
			{
				this._lgID = value;
			}
		}
		
		private string _teamID;
		public virtual string teamID
		{
			get
			{
				return this._teamID;
			}
			set
			{
				this._teamID = value;
			}
		}
		
		private string _franchID;
		public virtual string franchID
		{
			get
			{
				return this._franchID;
			}
			set
			{
				this._franchID = value;
			}
		}
		
		private string _divID;
		public virtual string divID
		{
			get
			{
				return this._divID;
			}
			set
			{
				this._divID = value;
			}
		}
		
		private short? _Rank;
		public virtual short? Rank
		{
			get
			{
				return this._Rank;
			}
			set
			{
				this._Rank = value;
			}
		}
		
		private short? _G;
		public virtual short? G
		{
			get
			{
				return this._G;
			}
			set
			{
				this._G = value;
			}
		}
		
		private short? _Ghome;
		public virtual short? Ghome
		{
			get
			{
				return this._Ghome;
			}
			set
			{
				this._Ghome = value;
			}
		}
		
		private short? _W;
		public virtual short? W
		{
			get
			{
				return this._W;
			}
			set
			{
				this._W = value;
			}
		}
		
		private short? _L;
		public virtual short? L
		{
			get
			{
				return this._L;
			}
			set
			{
				this._L = value;
			}
		}
		
		private string _DivWin;
		public virtual string DivWin
		{
			get
			{
				return this._DivWin;
			}
			set
			{
				this._DivWin = value;
			}
		}
		
		private string _WCWin;
		public virtual string WCWin
		{
			get
			{
				return this._WCWin;
			}
			set
			{
				this._WCWin = value;
			}
		}
		
		private string _LgWin;
		public virtual string LgWin
		{
			get
			{
				return this._LgWin;
			}
			set
			{
				this._LgWin = value;
			}
		}
		
		private string _WSWin;
		public virtual string WSWin
		{
			get
			{
				return this._WSWin;
			}
			set
			{
				this._WSWin = value;
			}
		}
		
		private short? _R;
		public virtual short? R
		{
			get
			{
				return this._R;
			}
			set
			{
				this._R = value;
			}
		}
		
		private short? _AB;
		public virtual short? AB
		{
			get
			{
				return this._AB;
			}
			set
			{
				this._AB = value;
			}
		}
		
		private short? _H;
		public virtual short? H
		{
			get
			{
				return this._H;
			}
			set
			{
				this._H = value;
			}
		}
		
		private short? _F_2B;
		public virtual short? F_2B
		{
			get
			{
				return this._F_2B;
			}
			set
			{
				this._F_2B = value;
			}
		}
		
		private short? _F_3B;
		public virtual short? F_3B
		{
			get
			{
				return this._F_3B;
			}
			set
			{
				this._F_3B = value;
			}
		}
		
		private short? _HR;
		public virtual short? HR
		{
			get
			{
				return this._HR;
			}
			set
			{
				this._HR = value;
			}
		}
		
		private short? _BB;
		public virtual short? BB
		{
			get
			{
				return this._BB;
			}
			set
			{
				this._BB = value;
			}
		}
		
		private short? _SO;
		public virtual short? SO
		{
			get
			{
				return this._SO;
			}
			set
			{
				this._SO = value;
			}
		}
		
		private short? _SB;
		public virtual short? SB
		{
			get
			{
				return this._SB;
			}
			set
			{
				this._SB = value;
			}
		}
		
		private short? _CS;
		public virtual short? CS
		{
			get
			{
				return this._CS;
			}
			set
			{
				this._CS = value;
			}
		}
		
		private short? _HBP;
		public virtual short? HBP
		{
			get
			{
				return this._HBP;
			}
			set
			{
				this._HBP = value;
			}
		}
		
		private short? _SF;
		public virtual short? SF
		{
			get
			{
				return this._SF;
			}
			set
			{
				this._SF = value;
			}
		}
		
		private short? _RA;
		public virtual short? RA
		{
			get
			{
				return this._RA;
			}
			set
			{
				this._RA = value;
			}
		}
		
		private short? _ER;
		public virtual short? ER
		{
			get
			{
				return this._ER;
			}
			set
			{
				this._ER = value;
			}
		}
		
		private double? _ERA;
		public virtual double? ERA
		{
			get
			{
				return this._ERA;
			}
			set
			{
				this._ERA = value;
			}
		}
		
		private short? _CG;
		public virtual short? CG
		{
			get
			{
				return this._CG;
			}
			set
			{
				this._CG = value;
			}
		}
		
		private short? _SHO;
		public virtual short? SHO
		{
			get
			{
				return this._SHO;
			}
			set
			{
				this._SHO = value;
			}
		}
		
		private short? _SV;
		public virtual short? SV
		{
			get
			{
				return this._SV;
			}
			set
			{
				this._SV = value;
			}
		}
		
		private int? _IPouts;
		public virtual int? IPouts
		{
			get
			{
				return this._IPouts;
			}
			set
			{
				this._IPouts = value;
			}
		}
		
		private short? _HA;
		public virtual short? HA
		{
			get
			{
				return this._HA;
			}
			set
			{
				this._HA = value;
			}
		}
		
		private short? _HRA;
		public virtual short? HRA
		{
			get
			{
				return this._HRA;
			}
			set
			{
				this._HRA = value;
			}
		}
		
		private short? _BBA;
		public virtual short? BBA
		{
			get
			{
				return this._BBA;
			}
			set
			{
				this._BBA = value;
			}
		}
		
		private short? _SOA;
		public virtual short? SOA
		{
			get
			{
				return this._SOA;
			}
			set
			{
				this._SOA = value;
			}
		}
		
		private int? _E;
		public virtual int? E
		{
			get
			{
				return this._E;
			}
			set
			{
				this._E = value;
			}
		}
		
		private int? _DP;
		public virtual int? DP
		{
			get
			{
				return this._DP;
			}
			set
			{
				this._DP = value;
			}
		}
		
		private double? _FP;
		public virtual double? FP
		{
			get
			{
				return this._FP;
			}
			set
			{
				this._FP = value;
			}
		}
		
		private string _name;
		public virtual string name
		{
			get
			{
				return this._name;
			}
			set
			{
				this._name = value;
			}
		}
		
		private string _park;
		public virtual string park
		{
			get
			{
				return this._park;
			}
			set
			{
				this._park = value;
			}
		}
		
		private int? _attendance;
		public virtual int? attendance
		{
			get
			{
				return this._attendance;
			}
			set
			{
				this._attendance = value;
			}
		}
		
		private int? _BPF;
		public virtual int? BPF
		{
			get
			{
				return this._BPF;
			}
			set
			{
				this._BPF = value;
			}
		}
		
		private int? _PPF;
		public virtual int? PPF
		{
			get
			{
				return this._PPF;
			}
			set
			{
				this._PPF = value;
			}
		}
		
		private string _teamIDBR;
		public virtual string teamIDBR
		{
			get
			{
				return this._teamIDBR;
			}
			set
			{
				this._teamIDBR = value;
			}
		}
		
		private string _teamIDlahman45;
		public virtual string teamIDlahman45
		{
			get
			{
				return this._teamIDlahman45;
			}
			set
			{
				this._teamIDlahman45 = value;
			}
		}
		
		private string _teamIDretro;
		public virtual string teamIDretro
		{
			get
			{
				return this._teamIDretro;
			}
			set
			{
				this._teamIDretro = value;
			}
		}
		
		private string _teamIDyearID;
		public virtual string teamIDyearID
		{
			get
			{
				return this._teamIDyearID;
			}
			set
			{
				this._teamIDyearID = value;
			}
		}
		
		private IList<Appearance> _Appearances = new List<Appearance>();
		public virtual IList<Appearance> Appearances
		{
			get
			{
				return this._Appearances;
			}
		}
		
	}
}
#pragma warning restore 1591
