#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace oDataModel	
{
	public partial class vSalaries_by_Year
	{
		private short _yearID;
		public virtual short yearID
		{
			get
			{
				return this._yearID;
			}
			set
			{
				this._yearID = value;
			}
		}
		
		private string _teamIDyearID;
		public virtual string teamIDyearID
		{
			get
			{
				return this._teamIDyearID;
			}
			set
			{
				this._teamIDyearID = value;
			}
		}
		
		private string _teamID;
		public virtual string teamID
		{
			get
			{
				return this._teamID;
			}
			set
			{
				this._teamID = value;
			}
		}
		
		private double? _salary;
		public virtual double? salary
		{
			get
			{
				return this._salary;
			}
			set
			{
				this._salary = value;
			}
		}
		
		private string _playerID;
		public virtual string playerID
		{
			get
			{
				return this._playerID;
			}
			set
			{
				this._playerID = value;
			}
		}
		
		private string _nameGiven;
		public virtual string nameGiven
		{
			get
			{
				return this._nameGiven;
			}
			set
			{
				this._nameGiven = value;
			}
		}
		
		private string _lgID;
		public virtual string lgID
		{
			get
			{
				return this._lgID;
			}
			set
			{
				this._lgID = value;
			}
		}
		
		private short? _G_all;
		public virtual short? G_all
		{
			get
			{
				return this._G_all;
			}
			set
			{
				this._G_all = value;
			}
		}
		
		private string _fullName;
		public virtual string fullName
		{
			get
			{
				return this._fullName;
			}
			set
			{
				this._fullName = value;
			}
		}
		
	}
}
#pragma warning restore 1591
