#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace oDataModel	
{
	public partial class vTeams_by_Year
	{
		private short _yearID;
		public virtual short yearID
		{
			get
			{
				return this._yearID;
			}
			set
			{
				this._yearID = value;
			}
		}
		
		private string _teamID;
		public virtual string teamID
		{
			get
			{
				return this._teamID;
			}
			set
			{
				this._teamID = value;
			}
		}
		
		private short? _Rank;
		public virtual short? Rank
		{
			get
			{
				return this._Rank;
			}
			set
			{
				this._Rank = value;
			}
		}
		
		private string _teamIDyearID;
		public virtual string teamIDyearID
		{
			get
			{
				return this._teamIDyearID;
			}
			set
			{
				this._teamIDyearID = value;
			}
		}
		
	}
}
#pragma warning restore 1591
